"""initialize 5

Revision ID: 27b10bccbf04
Revises: be770c7573ca
Create Date: 2024-07-01 11:23:09.199599

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '27b10bccbf04'
down_revision = 'be770c7573ca'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('product', sa.Column('image_url', sa.String(length=200), nullable=True))
    op.add_column('product', sa.Column('is_featured', sa.Boolean(), nullable=True))
    op.add_column('product', sa.Column('featured_priority', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('product', 'featured_priority')
    op.drop_column('product', 'is_featured')
    op.drop_column('product', 'image_url')
    # ### end Alembic commands ###
