"""Add phone, location, and mpesaNumber to user model

Revision ID: f96b24d7cc7b
Revises: ccc550e6f9f8
Create Date: 2024-07-25 16:09:13.516510

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f96b24d7cc7b'
down_revision = 'ccc550e6f9f8'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('phone', sa.String(length=10), nullable=True))
        batch_op.add_column(sa.Column('location', sa.String(length=255), nullable=True))
        batch_op.add_column(sa.Column('mpesaNumber', sa.String(length=50), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_column('mpesaNumber')
        batch_op.drop_column('location')
        batch_op.drop_column('phone')

    # ### end Alembic commands ###
